version: '3'
services:
  app:
    build: .
    ports:
      - 5000:5000

  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: adrien
    volumes:
      - data:/var/lib/mysql

  adminer:
    image: phpmyadmin:latest
    ports:
      - 8080:80

volumes:
  data:
