version: '3'
services:
  app:
    build: .
    container_name: python
    ports:
      - 5000:5000

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: adrien
    volumes:
      - ./mysql_volume:/var/lib/mysql



  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  data:
